apiVersion: v1
kind: Pod
metadata:
  name: aha-pod
spec:
  containers:
  - name: container-name
    image: jinwei/imagehome:latest
    command: ["/bin/sh"]
    args: ["-c", "sleep 36500000"]
    imagePullPolicy: Always
    resources:
      limits:
        nvidia.com/gpu: 1
        memory: 2Gi
        cpu: 2
      requests:
        nvidia.com/gpu: 1
        memory: 2Gi
        cpu: 1
  restartPolicy: Never