apiVersion: v1
kind: Pod
metadata:
  name: carlsim5
spec:
  containers:
  - name: container-name
    image: jinwei/carlsim5:cuda10.2
    args: ["sleep", "36500000"]
    imagePullPolicy: Always
    resources:
      limits:
        nvidia.com/gpu: '1'
        memory: 8Gi
        cpu: '2'
      requests:
        nvidia.com/gpu: '1'
        memory: 2Gi
        cpu: '1'
  restartPolicy: Never
  nodeSelector:
    gpu-type: 1080Ti